[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "social_media_sentiments_analysis"
version = "0.0.1"
description = "This is my analysis of the data."
authors = [
  { name = "Tran Ngo Nhat Nam" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.12"


[tool.ruff]
line-length = 99
src = ["social_media_sentiments_analysis"]
include = ["pyproject.toml", "social_media_sentiments_analysis/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["social_media_sentiments_analysis"]
force-sort-within-sections = true

